<?php

/**
 * This is example code for a Drupal 6 to Drupal 7 migration. This won't actually
 * work without defining the referenced vocabularies, content types, and fields
 * on each side.
 */

/**
 * Implements hook_flush_caches().
 * This will register the migrations when the caches are flushed.
 * However, it looks like this might also be possible through the UI
 */
function d6d7_flush_caches() {
  d6d7_register_migrations();
}

/**
 * Register all D6->D7 migrations.
 */
function d6d7_register_migrations() {
  /**
   * Each migration being registered takes an array of arguments, some required
   * and some optional. Start with the common arguments required by all - the
   * source_connection (connection key, set up in settings.php, pointing to
   * the Drupal 6 database) and source_version (major version of Drupal).
   * The connection key should be added to the settings.php file.
   * e.g.
   * $databases['legacy']['default'] = array(
   *   'driver' => 'mysql',
   *   'database' => '',
   *   'username' => '',
   *   'password' => '',
   *   'host' => '',
   *   'prefix' => '',
   * );
   */
  $common_arguments = array(
    'source_connection' => 'legacy',
    'source_version' => 6,
  );

  // The description and the migration machine name are also required arguments,
  // which will be unique for each migration you register.
  $arguments = $common_arguments + array(
    'description' => t('Migration of users from Drupal 6'),
    'machine_name' => 'User',
  );

  // We just use the migrate_d2d D6 migration class as-is.
  Migration::registerMigration('d6d7WebAuthUserMigration', $arguments['machine_name'],
                               $arguments);

  // For vocabulary migrations, source_vocabulary and destination_vocabulary are
  // required arguments. Note that in Drupal 6 vocabularies did not have machine
  // names, so we use the vocabulary ID to uniquely identify them.
  $vocabulary_arguments = array(
    array(
      'description' => t('Migration of Catalog Categories terms from Drupal 6'),
      'machine_name' => 'Catalog_Categories',
      'source_vocabulary' => '1',  // D6 Vocabulary ID
      'destination_vocabulary' => 'catalog_categories',
    ),
  );

  // Again, we're using the migrate_d2d class directly.
  // The soft dependency says that while we don't have to run the user migration
  // first, we want to make sure it's listed first so the vocubularies are
  // listed right ahead of the node migrations.
  $common_vocabulary_arguments = $common_arguments + array(
    'class_name' => 'd6d7CatalogCategoriesMigration',
    'soft_dependencies' => array('User'),
  );

  foreach ($vocabulary_arguments as $arguments) {
    $arguments += $common_vocabulary_arguments;
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'],
                                 $arguments);
  }

  // Node migrations - each has its own class derived from the migrate_d2d class,
  // specifying its particular field mappings and transformations. source_type
  // and destination_type are required arguments.
  $node_arguments = array(
    array(
      'class_name' => 'd6d7CatalogEntryMigration',
      'description' => t('Migration of Catalog Entries from Drupal 6'),
      'machine_name' => 'CatalogEntry',
      'source_type' => 'service',
      'destination_type' => 'catalog_entry',
//      'dependencies' => array('CatalogCategories',),
    ),
	array(
	  'class_name' => 'd6d7OfficialServiceMigration',
	  'description' => t('Migration of Official Service Data'),
	  'machine_name' => 'OfficialService',
	  'source_type' => 'service',
	  'destination_type' => 'official_its_service',
    ),
	array(
	  'class_name' => 'd6d7ServicePageMigration',
	  'description' => t('Migration of Official Service Data'),
	  'machine_name' => 'ServicePage',
	  'source_type' => 'service',
	  'destination_type' => 'service_page',
    ),
  );

  // Tell the node migrations where the users are coming from, so they can
  // set up the dependency and resolve D6->D7 uids.
  $common_node_arguments = $common_arguments + array(
//    'user_migration' => 'User',
  );

  foreach ($node_arguments as $arguments) {
    $arguments = array_merge_recursive($arguments, $common_node_arguments);
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'],
                                 $arguments);
  }
/*
  // Menu migrations -- same requirements as users
  $menu_arguments = $common_arguments + array(
    'description' => t('Migration of menus from Drupal 6'),
    'machine_name' => 'Menu',
  );

  // We just use the migrate_d2d D6 migration class as-is.
  Migration::registerMigration('DrupalMenu6Migration', $menu_arguments['machine_name'],
                               $menu_arguments);

  // Menu links migrations -- basic requirements, plus must set up menu dependency
  $menu_links_arguments = $common_arguments + array(
    'description' => t('Migration of menu links from Drupal 6'),
    'machine_name' => 'MenuLinks',
    'menu_migration' => $menu_arguments['machine_name'],
  );
  Migration::registerMigration('DrupalMenuLinks6Migration', $menu_links_arguments['machine_name'],
                               $menu_links_arguments);
*/
}

/**
 * Implements hook_migrate_api().
 */
function d6d7_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}
